server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/punisyscustomer
    username: root
    password: penaldo10
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: customer-service


eureka:
  instance:
    instance-id: =${spring.application.name}:${random.uuid}

