server:
  port: 8134

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8082  # Direcci贸n de tu microservicio de productos
          predicates:
            - Path=/products/**

        - id: customer-service
          uri: http://localhost:8081  # Direcci贸n de tu microservicio de clientes
          predicates:
            - Path=/customers/**

        - id: supplier-service
          uri: http://localhost:8083  # Direcci贸n de tu microservicio de proveedores
          predicates:
            - Path=/suppliers/**

      # Configuraci贸n CORS si necesitas permitir peticiones de tu frontend
      globalcors:
        cors-mappings:
          - allowed-origins: "*"
            allowed-methods: "*"

eureka:
  instance:
    instance-id: =${spring.application.name}:${random.uuid}