server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/punisysproduct
    username: root
    password: penaldo10
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: product-service


eureka:
  instance:
    instance-id: =${spring.application.name}:${random.uuid}
