spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/punigonzalez/PuniSys-configuration-repo #url de donde estan las config
          clone-on-start: true   # para que cuando se inicie el servicio, haga el clonado del repositorio

server:
  port: 8889

eureka:
  instance:
    instance-id: =${spring.application.name}:${random.uuid}