server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/punisyssupplier
    username: root
    password: penaldo10
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: supplier-service

eureka:
  instance:
    instance-id: =${spring.application.name}:${random.uuid}
